services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data     # <-- DB dosyasını host ile paylaş
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    command: python -m app.workers.worker
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data     # <-- web ile aynı DB dosyası
    depends_on:
      - redis
    restart: unless-stopped
